#!/usr/bin/env python3

"""
csrf-poc-gen — CSRF PoC Generator
Matches Burp Suite Professional's "Generate CSRF PoC" output exactly.
For authorized security testing only.
"""

import sys
import os
import argparse
import urllib.parse


# ──────────────────────────────────────────────
# Input
# ──────────────────────────────────────────────

def read_raw(source: str) -> str:
    if source == "-":
        if sys.stdin.isatty():
            print("[*] Paste your raw HTTP request below.")
            print("    Press Enter twice then Ctrl-D (Linux/Mac) or Ctrl-Z+Enter (Windows) when done.\n")
        return sys.stdin.read()
    if not os.path.isfile(source):
        print(f"[!] File not found: {source}")
        sys.exit(1)
    with open(source, "r") as f:
        return f.read()


# ──────────────────────────────────────────────
# Parsing
# ──────────────────────────────────────────────

def parse_request(raw: str):
    lines = raw.splitlines()

    # Strip leading blank lines (common when pasting)
    while lines and not lines[0].strip():
        lines.pop(0)

    if not lines:
        print("[!] Empty request — nothing to parse.")
        sys.exit(1)

    parts = lines[0].split()
    if len(parts) < 3:
        print(f"[!] Could not parse request line: {lines[0]!r}")
        sys.exit(1)

    method, full_path, http_version = parts[0].upper(), parts[1], parts[2]

    headers, body, in_body = {}, "", False
    for line in lines[1:]:
        if not in_body and line.strip() == "":
            in_body = True
            continue
        if in_body:
            body += line.strip()
        elif ":" in line:
            k, v = line.split(":", 1)
            headers[k.strip().lower()] = v.strip()

    host   = headers.get("host", "")
    scheme = "https" if http_version == "HTTP/2" else "http"
    path_only, query_string = full_path.split("?", 1) if "?" in full_path else (full_path, "")
    base_url = f"{scheme}://{host}{path_only}"

    return method, base_url, query_string, body


# ──────────────────────────────────────────────
# Encoding & HTML building
# ──────────────────────────────────────────────

def parse_params(data: str):
    if not data:
        return []
    return urllib.parse.parse_qsl(data, keep_blank_values=True)


_SAFE = set("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_")

def html_entity_encode(value: str) -> str:
    return "".join(c if c in _SAFE else f"&#{ord(c)};" for c in value)


def build_hidden_inputs(params) -> str:
    return "".join(
        f'      <input type="hidden" name="{k}" value="{html_entity_encode(v)}" />\n'
        for k, v in params
    )


# ──────────────────────────────────────────────
# PoC generators
# ──────────────────────────────────────────────

def generate_poc(method: str, base_url: str, query_string: str, body: str) -> str:
    if method == "GET":
        inputs     = build_hidden_inputs(parse_params(query_string))
        form_open  = f'<form action="{base_url}">'
    else:
        inputs     = build_hidden_inputs(parse_params(body))
        form_open  = f'<form action="{base_url}" method="POST">'

    return (
        f'<html>\n'
        f'  <!-- CSRF PoC - generated by csrf_poc_gen.py -->\n'
        f'  <body>\n'
        f'    {form_open}\n'
        f'{inputs}'
        f'      <input type="submit" value="Submit request" />\n'
        f'    </form>\n'
        f'    <script>\n'
        f"      history.pushState('', '', '/');\n"
        f'      document.forms[0].submit();\n'
        f'    </script>\n'
        f'  </body>\n'
        f'</html>\n'
    )


# ──────────────────────────────────────────────
# CLI
# ──────────────────────────────────────────────

BANNER = """\033[1;36m
  ___ ___ ___  _____   ___  ___ ___    __ _ ___ _ __
 / __/ __| _ \\| __| \\ / / \\/ __|  _|  / _` / -_) '  \\
| (__\\__ |   /| _|  V /| >  < (_ | _|| (_| \\__/ |_|_|
 \\___|___|_|_\\|_|   \\_//_/_/\\_\\___|___|\\__, |\\___|_|_|
                                        |___/
\033[0m\033[90m  Burp-compatible CSRF PoC Generator  \033[0m
"""

EXAMPLES = """\
examples:
  # File input
  csrf-poc-gen request.txt
  csrf-poc-gen request.txt -o /tmp/poc.html

  # Stdin / pipe  (use - as the input)
  csrf-poc-gen -                          # interactive paste, then Ctrl-D
  cat request.txt | csrf-poc-gen -        # pipe from file
  pbpaste | csrf-poc-gen -                # pipe from clipboard (Mac)
  xclip -o | csrf-poc-gen -              # pipe from clipboard (Linux)

  # Print to stdout instead of saving
  cat request.txt | csrf-poc-gen - --stdout

  # Suppress the banner (useful in scripts)
  csrf-poc-gen request.txt --no-banner
"""


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="csrf-poc-gen",
        description=(
            "Generate a CSRF PoC HTML file from a raw HTTP request.\n"
            "Output matches Burp Suite Professional's 'Generate CSRF PoC' exactly."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=EXAMPLES,
        add_help=False,          # we add our own -h / --help / -help below
    )

    # ── positional ──────────────────────────────────────────────────────────
    parser.add_argument(
        "input",
        metavar="REQUEST",
        nargs="?",               # optional so -help alone doesn't error
        help="Path to raw HTTP request file  |  '-' to read from stdin (paste or pipe)",
    )

    # ── output options ──────────────────────────────────────────────────────
    out = parser.add_argument_group("output options")
    out.add_argument(
        "-o", "--output",
        metavar="FILE",
        default="csrf_poc.html",
        help="Output file path  (default: csrf_poc.html)",
    )
    out.add_argument(
        "--stdout",
        action="store_true",
        help="Print PoC HTML to stdout instead of saving to a file",
    )

    # ── display options ─────────────────────────────────────────────────────
    disp = parser.add_argument_group("display options")
    disp.add_argument(
        "--no-banner",
        action="store_true",
        help="Suppress the ASCII art banner",
    )

    # ── help — accept -h, --help, and -help ─────────────────────────────────
    disp.add_argument(
        "-h", "--help", "-help",
        action="help",
        default=argparse.SUPPRESS,
        help="Show this help message and exit",
    )

    return parser


def main():
    parser = build_parser()
    args   = parser.parse_args()

    # Show help when called with no arguments
    if not args.input:
        parser.print_help()
        sys.exit(0)

    if not args.no_banner and not args.stdout:
        print(BANNER)

    try:
        raw    = read_raw(args.input)
        method, base_url, query_string, body = parse_request(raw)

        if method not in ("GET", "POST"):
            print(f"[!] Unsupported HTTP method: {method}")
            sys.exit(1)

        html       = generate_poc(method, base_url, query_string, body)
        params_src = query_string if method == "GET" else body
        param_keys = [k for k, _ in parse_params(params_src)]

        if args.stdout:
            print(html)
        else:
            with open(args.output, "w") as f:
                f.write(html)
            print(f"\033[1;32m[+]\033[0m PoC saved   : \033[1m{args.output}\033[0m")
            print(f"    Method    : {method}")
            print(f"    Target    : {base_url}")
            print(f"    Params    : {param_keys}")

    except KeyboardInterrupt:
        print("\n[!] Aborted.")
        sys.exit(1)
    except Exception as e:
        print(f"[!] Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()